### ISSUE TITLE
registration page - user thank you emails

### ISSUE THREAD

**Issue by autoboxer** [autoboxer/MARE#125]
### Tasks

- [ ] call the email service ( emails_register.js ) with the user object
- [ ] build the template and populate it with a thank you message as well as any details like how long it will take to activate **( see Jared, Lisa, and Bridget for details )**
- [ ] handle any errors via console.error() messages
- [ ] change any environment variables necessary

### Definition of Done

- [ ] Jared and performed a code review
- [ ] Lisa and Bridget have signed off on the email content
- [ ] changes to email environment variables have been communicated to the team
