### ISSUE TITLE
registration page - account verification emails

### ISSUE THREAD

**Issue by autoboxer** [autoboxer/MARE#126]
### Tasks

- [x] create a account verification model on save for each user type
- [x] call the email service ( emails_register.js ) with the user object ( this call may happen in a post-save hook in each of the model definitions )
- [x] build the template and populate it with a verify account message as well as a link and details about when their account will be deactivated **( see Jared, Lisa, and Bridget for details )**
- [x] handle any errors via console.error() messages
- [x] change any environment variables necessary
- [x] create a route for handling user clicks in the emails, which should update the model, checking the **account verified** checkbox, and delete the verification model if successful
- [ ] if the account verification model can't be found, the user should be redirected to the home page with a flash message outlining the issue **( see Jared, Lisa, and Bridget for details )**

### Definition of Done

- [ ] Jared and performed a code review
- [ ] Lisa and Bridget have signed off on the email content
- [ ] changes to email environment variables have been communicated to the team
