### ISSUE TITLE
registration page - staff emails

### ISSUE THREAD

**Issue by autoboxer** [autoboxer/MARE#17]
### Tasks

- [x] fetch the CSC staff member associated with user registration and extract their email
- [x] call the email service ( emails_register.js ) with the admin object
- [x] build the template and populate it with all details about the new user, a link to the model, and any fields that need to be updated manually **( see Jared, Lisa, and Bridget for details )**.  **Note:** This may require multiple functions and multiple templates.
- [x] handle any errors via console.error()
- [x] change any environment variables necessary

### Notes

- the information will need to be entered in the old MARE system to keep it up to date until it's decommissioned, so it's important they are provided with all submitted details.
- if file uploads don't end up being possible, the email needs to include the homestudy file upload as an attachment **( see Jared when you get here )**

### Definition of Done

- [x] Jared and performed a code review
- [x] Lisa and Bridget have signed off on the email content
- [x] changes to email environment variables have been communicated to the team
