### ISSUE TITLE
update the privacy policy

### ISSUE THREAD

**Issue by autoboxer** [autoboxer/MARE#233]
### Tasks

- [x] review the privacy policy document for accuracy
- [x] update the privacy policy with the new text

### Definition of Done

- [x] the privacy policy page has the correct text
- [x] the privacy policy page is formatted in a readable way

**Comment by lisafunaro** [comment]
The new privacy policy is up in production!


Lisa K. Funaro
Executive Director
Massachusetts Adoption Resource Exchange

[MARE]<http/:www.mareinc.org>

We find adoptive homes for children and teens in foster care.

19 Needham Street, Suite 206 | Newton, MA 02461

Telephone: (617) 964-6273 ext. 113

Website<http://www.mareinc.org> | Facebook<https://www.facebook.com/massadopt/> | Twitter<https://twitter.com/Mass_Adopt> | Instagram<https://www.instagram.com/mass_adopt/>
