### ISSUE TITLE
add donation processing to the donations page

### ISSUE THREAD

**Issue by autoboxer** [autoboxer/MARE#25]
### Tasks

- [x] wire up stripe processing
- [x] handle set donation amounts
- [x] handle user entered donation amounts ( I think this is best done by creating a donation amount of $0.01, and dynamically multiplying it depending on the amount they enter )
- [x] handle recurring donations
- [x] create a success/error flash message to inform the user of the status of their donation
- [x] create a donation model to store information about the amount, date, and a link to the user who donated
- [x] wire it up to create a new donation model whenever a donation is successful ( they will be used to display donation history on a users account page
- [x] add a reference to the Donations made in each of the user models ( site visitor, family, social worker, and admin )

### Definition of Done

- [ ] Jared has reviewed the code
- [ ] Lisa and Bridget think the implementation is awesome
