### ISSUE TITLE
create the base layout for the account page

### ISSUE THREAD

**Issue by autoboxer** [autoboxer/MARE#252]
### Tasks

- [x] create a two column layout that's about 200px in a fixed width bar on the left, and an area on the right that takes up the remaining space.  This should be done in **_page-account.scss**
- [x] update the **account.hbs** template with the necessary markup

### Notes

the left column will be a list of options depending on the user type.  For instance, a family may have the option to view **children**, **events**, etc..  On click, details of the target content will load into the right panel.

### Definition of Done

- [x] Jared has reviewed the code

**Comment by patnealcodes** [comment]
Ready for review in feature/account-page
