### ISSUE TITLE
add user info to the account page

### ISSUE THREAD

**Issue by autoboxer** [autoboxer/MARE#372]
### Tasks

- [x] use the data in the **req.user** object in the **account.js** Express view to pull in useful user information.
- [x] populate the account template **account.hbs** with the user data in the right pane (the user account information will be selected and displayed by default
- [ ] create an ajax function to call a service in **service_account.js** which will update a group of fields.  This can be done by sending the fields in an array or object, and using the data to fetch and update the user object.  The status of the action should be returned to the user
- [ ] create a message container to display the status of the update function to the user

### Notes

It's expected that you'll need Jared's help for several of these tasks, ask away and I'll help you build out the node side.

### Definition of Done

- [ ] Jared has reviewed the code
- [ ] Lisa and Bridget think to panel looks awesome
