### ISSUE TITLE
finish placements import

### ISSUE THREAD

**Issue by lisafunaro** [autoboxer/MARE#396]
### Tasks

- [x] import placements from the old system, branching out matches, placements, legalizations and disruptions into the newly created models for each.
- [x] import sources, which should only be applied to the latest record for matches, placements, disruptions, and legalizations.
- [x] fix the family agency field so it’s always there, no matter if the family is registered in the system or not.
- [x] add agency for registered families automatically when we fetch their record.  Apply the agency to all records associated with them, not just the latest.
- [x] ensure duplicates are not being created.

### Definition of Done

- [x] placements have been imported from the old system and created as matches, placements, legalizations, and disruptions depending on the information contained in each.
- [x] the family agency field is present whether the family is registered with MARE or not
- [x] placements have a family agency listed for all records with a registered family who has a social worker listed.
- [x] sources are present for the most recent match, placement, legalization, and disruption for a particular child.
- [x] there are no duplicates in the system.

**Comment by lisafunaro** [comment]
Done!

Lisa K. Funaro
Executive Director
Massachusetts Adoption Resource Exchange

[MARE]<http/:www.mareinc.org>

We find adoptive homes for children and teens in foster care.

19 Needham Street, Suite 206 | Newton, MA 02461

Telephone: (617) 964-6273 ext. 113

Website<http://www.mareinc.org> | Facebook<https://www.facebook.com/massadopt/> | Twitter<https://twitter.com/Mass_Adopt> | Instagram<https://www.instagram.com/mass_adopt/>
