### ISSUE TITLE
fix spelling error in inquiry emails

### ISSUE THREAD

**Issue by autoboxer** [autoboxer/MARE#400]
### Tasks

- [ ] change the spelling from inquiriy to inquiry at the bottom of general inquiry emails to MARE
- [ ] change the spelling from inquiriy to inquiry at the bottom of child inquiry emails to MARE

### Definition of Done

- [ ] inquiry is spelled correctly in general inquiry email to MARE
- [ ] inquiry is spelled correctly in child inquiry email to MARE
