### ISSUE TITLE
update general inquiry email to MARE

### ISSUE THREAD

**Issue by autoboxer** [autoboxer/MARE#402]
### Tasks

- [ ] group the fields in a more readable way
- [ ] have email originate from inquirer
- [ ] add family email
- [ ] add family date of birth
- [ ] add family gender
- [ ] add family ethnicity
- [ ] add family stage in process
- [ ] add family social worker
- [ ] add the mare logo to the email header

### Definition of Done

- [ ] the fields are grouped in a readable way
- [ ] the email originates from the inquirer
- [ ] the family email, date of birth, gender, ethnicity, stage in the process, and social worker are present in the email
- [ ] the mare logo is present in the header of the email
