### ISSUE TITLE
remove legal disclosure language on bottom of event registration form

### ISSUE THREAD

**Issue by autoboxer** [autoboxer/MARE#403]
### Tasks

- [ ] remove legal disclosure language for logged in site visitors
- [ ] remove legal disclosure language for logged in site visitors
- [ ] remove legal disclosure language for logged in site visitors
