### ISSUE TITLE
fix attachments not appearing in the old system

### ISSUE THREAD

**Issue by autoboxer** [autoboxer/MARE#406]
### Description of the Bug

In the old system, when trying to view attachments, it instead loads the new website into the iFrame where they should be.

### Tasks

- [ ] talk to Brian about gaining access to the old code, or the possibility of redirecting that specific - [ ] - - [ ] traffic to the attachments page.
- [ ] implement code to display the current attachments for children
- [ ] implement code to display the current attachments for families

### Definition of Done

- [ ] attachments can be accessed via the old system
