### ISSUE TITLE
children with siblingGroupImage === null won't display in the admin UI

### ISSUE THREAD

**Issue by autoboxer** [autoboxer/MARE#408]
### Tasks

- [ ] determine what causes a null value in the siblingGroupImage field
- [ ] update the code to prevent `null` values in the siblingGroupImage field

### Definition of Done

- [ ] problematic child details appear in the admin UI
- [ ] null values are no longer being saved to children records in the siblingGroupImage field

### Notes

this was discovered in child 6791 who had a null value in the siblingGroupImage field, however, his sibling 6792 didn't have a value set for the field.
