### ISSUE TITLE
handle bad routes

### ISSUE THREAD

**Issue by autoboxer** [autoboxer/MARE#411]
### Tasks

- [ ] update any routes with wildcards to send the user to the base route if no data matches the wildcard
- [ ] send unknown routes from a particular site area to that site area
- [ ] send unknown routes to the 404 page

### Definition of Done

- [ ] nonsensical wildcards routes display the appropriate page for the user
- [ ] nonsensical routes  in a subarea display the appropriate page for the user
- [ ] nonsensical routes display the 404 page for the user
