### ISSUE TITLE
events - confirmation email

### ISSUE THREAD

**Issue by autoboxer** [autoboxer/MARE#96]
### Tasks

- [ ] call the email service ( emails_event.js ) with the req object to extract req.user and req.body
- [ ] build the template and populate it with a summary of the event **( see Jared, Lisa, and Bridget for details )**.
- [ ] handle any errors via console.error()
- [ ] change any environment variables necessary

### Definition of Done

- [ ] Jared and performed a code review
- [ ] Lisa and Bridget have signed off on the email content
- [ ] changes to email environment variables have been communicated to the team
